server:
  port: 80
eureka:
  client:
    register-with-eureka: true #false表示自己不向注册中心注册
    fetch-registry: true #表示自己端就是注册中心，我的职责就是维护服务实例，并不要去检索服务
    service-url:
      #设置于EurekaServer交互的地址查询服务和注册服务都需要依赖这个
      #      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka
      defaultZone: http://127.0.0.1:7001/eureka
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #      采样率值介于0到1之间，1表示全部采用
      probability: 1