server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名
  client:
    register-with-eureka: false #false表示自己不向注册中心注册
    fetch-registry: false #表示自己端就是注册中心，我的职责就是维护服务实例，并不要去检索服务
    service-url:
      #设置于EurekaServer交互的地址查询服务和注册服务都需要依赖这个
      defaultZone: http://127.0.0.1:7001/eureka/
  server:
    #关闭自我保护机制，保证不可用服务被及时清理
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000