server:
  port: 7002
eureka:
  instance:
    hostname: localhost #eureka服务端的实例名
  client:
    register-with-eureka: false #false表示自己不向注册中心注册
    fetch-registry: false #表示自己端就是注册中心，我的职责就是维护服务实例，并不要去检索服务
    service-url:
      #设置于EurekaServer交互的地址查询服务和注册服务都需要依赖这个
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/